services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ory
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ory"]
      interval: 10s
      timeout: 5s
      retries: 5

  kratos:
    image: oryd/kratos:latest
    depends_on:
      - postgres
    environment:
      DSN: postgres://ory:secret@postgres:5432/ory?sslmode=disable
      KRATOS_PUBLIC_URL: http://localhost:4433/
      KRATOS_ADMIN_URL: http://localhost:4434/
      KRATOS_UI_URL: http://localhost:3000/
    ports:
      - "4433:4433"
      - "4434:4434"
    command:
      - serve
      - --config
      - /etc/kratos/kratos.yml
    volumes:
      - ./ory/config/kratos.yml:/etc/kratos/kratos.yml:ro

volumes:
  pgdata:
