services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ory
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ory"]
      interval: 10s
      timeout: 5s
      retries: 5

  # hydra:
  #   image: oryd/hydra:latest
  #   depends_on:
  #     - postgres
  #   environment:
  #     DSN: postgres://ory:secret@postgres:5432/ory?sslmode=disable
  #     URLS_SELF_ISSUER: http://localhost:4444/
  #     URLS_CONSENT: http://localhost:3000/consent
  #     URLS_LOGIN: http://localhost:3000/login
  #     SECRETS_SYSTEM: youReallyNeedToChangeThis
  #   ports:
  #     - "4444:4444"
  #     - "4445:4445"
  #   command:
  #     - serve
  #     - all
  #     - -c /etc/hydra/config.yml
  #     - --dev
  #     - --sqa-opt-out
  #   volumes:
  #     - ./ory/hyrda/config.yml:/etc/hydra/config.yml:ro

  kratos:
    image: oryd/kratos:latest
    depends_on:
      - postgres
    environment:
      DSN: postgres://ory:secret@postgres:5432/ory?sslmode=disable
      KRATOS_PUBLIC_URL: http://localhost:4433/
      KRATOS_ADMIN_URL: http://localhost:4434/
      KRATOS_UI_URL: http://localhost:3000/
    ports:
      - "4433:4433"
      - "4434:4434"
    command:
      - serve
      - --config
      - /etc/kratos/kratos.yml
    volumes:
      - ./kratos/config/kratos.yml:/etc/kratos/kratos.yml:ro

  # keto:
  #   image: oryd/keto:latest
  #   depends_on:
  #     - postgres
  #   environment:
  #     DSN: postgres://ory:secret@postgres:5432/ory?sslmode=disable
  #     KETO_READ_REMOTE: http://localhost:4466
  #     KETO_WRITE_REMOTE: http://localhost:4467
  #   ports:
  #     - "4466:4466"
  #     - "4467:4467"
  #   command:
  #     - serve
  #     - --config
  #     - /etc/keto/keto.yml
  #   volumes:
  #     - ./keto/config/keto.yml:/etc/keto/keto.yml:ro

volumes:
  pgdata:
